# Usamos una imagen ligera de Python
FROM python:3.11-slim

# Directorio de trabajo
WORKDIR /app

# 1. Instalamos librerías
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 2. Copiamos TODOS los scripts y json de la carpeta actual
COPY . .

# 3. Comando por defecto
CMD ["python", "main.py"]

#para ejecutar:
# docker build -t generador-padres .

# docker run --rm -v "${PWD}:/app" `
#   -e API_URL="http://host.docker.internal:8000" `
#   -e PROYECTO_REGION_INSTANCIA="tuyos:region:instancia" `
#   -e USUARIO_DB="postgres" `
#   -e CONTR_DB="tu_contrasena" `
#   -e NOMBRE_BD="tu_bd" `
#   generador-padres