# Usamos Python ligero
FROM python:3.11-slim

# Directorio de trabajo
WORKDIR /app

# Copiamos requirements e instalamos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos TODOS los archivos de la carpeta actual
COPY . .

# Comando por defecto
CMD ["python", "main.py"]