FROM python:3.11-slim

WORKDIR /app

# Copiamos requirements e instalamos
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamos TODOS los archivos de la carpeta actual
COPY . .

# Ejecutamos el script con su nuevo nombre
CMD ["python", "main.py"]